# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

INITIAL_POSITIONS = ('Manager', 'Full Time', 'Student Lead', 'Supervisor', 'Student')


def populate_position(apps, schema_editor):
    Position = apps.get_model('employees', 'Position')
    for p in INITIAL_POSITIONS:
        Position.objects.create(title=p)


def undo_populate_position(apps, schema_editor):
    Position = apps.get_model('employees', 'Position')
    for p in Position.objects.all():
        p.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_position, undo_populate_position),
    ]
