# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('up_for_sub', models.BooleanField(default=False)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='employees.Employee')),
                ('employee_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_schedule_set', to='employees.Employee')),
            ],
        ),
    ]
