# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_schedule_set', to='employees.Employee'),
        ),
    ]
