# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

INITIAL_CATEGORIES = ('Produce', 'Meat', 'Freezer', 'Dry Goods', 'Cleaning Supplies')
INITIAL_LOCATIONS = ('Freezer A', 'Freezer B', 'Cooler A', 'Cooler B', 'Dry Storage', 'Supplies')


def populate_category(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    for c in INITIAL_CATEGORIES:
        Category.objects.create(name=c)


def undo_populate_category(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    for c in Category.objects.all():
        c.delete()


def populate_location(apps, schema_editor):
    Location = apps.get_model('inventory', 'Location')
    for c in INITIAL_LOCATIONS:
        Location.objects.create(name=c)


def undo_populate_location(apps, schema_editor):
    Location = apps.get_model('inventory', 'Location')
    for c in Location.objects.all():
        c.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('units', models.SmallIntegerField(default=0, verbose_name=((0, 'Count'), (1, 'Pounds'), (2, 'Ounces'), (3, 'Liters')))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
        migrations.RunPython(populate_category, undo_populate_category),
        migrations.RunPython(populate_location, undo_populate_location),
    ]
